/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductionTdsQcRouteImport } from './routes/production.tds-qc'
import { Route as ProductionStageTrackingRouteImport } from './routes/production.stage-tracking'
import { Route as ProductionRmRequestRouteImport } from './routes/production.rm-request'
import { Route as ProductionRmReceiptRouteImport } from './routes/production.rm-receipt'
import { Route as ProductionOrdersRouteImport } from './routes/production.orders'
import { Route as ProductionCuttingApprovalRouteImport } from './routes/production.cutting-approval'
import { Route as ProductionOrdersIndexRouteImport } from './routes/production.orders.index'
import { Route as ProductionOrdersOrderIdRouteImport } from './routes/production.orders.$orderId'

const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionTdsQcRoute = ProductionTdsQcRouteImport.update({
  id: '/tds-qc',
  path: '/tds-qc',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionStageTrackingRoute = ProductionStageTrackingRouteImport.update({
  id: '/stage-tracking',
  path: '/stage-tracking',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionRmRequestRoute = ProductionRmRequestRouteImport.update({
  id: '/rm-request',
  path: '/rm-request',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionRmReceiptRoute = ProductionRmReceiptRouteImport.update({
  id: '/rm-receipt',
  path: '/rm-receipt',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionOrdersRoute = ProductionOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionCuttingApprovalRoute =
  ProductionCuttingApprovalRouteImport.update({
    id: '/cutting-approval',
    path: '/cutting-approval',
    getParentRoute: () => ProductionRoute,
  } as any)
const ProductionOrdersIndexRoute = ProductionOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductionOrdersRoute,
} as any)
const ProductionOrdersOrderIdRoute = ProductionOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => ProductionOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/production': typeof ProductionRouteWithChildren
  '/production/cutting-approval': typeof ProductionCuttingApprovalRoute
  '/production/orders': typeof ProductionOrdersRouteWithChildren
  '/production/rm-receipt': typeof ProductionRmReceiptRoute
  '/production/rm-request': typeof ProductionRmRequestRoute
  '/production/stage-tracking': typeof ProductionStageTrackingRoute
  '/production/tds-qc': typeof ProductionTdsQcRoute
  '/production/orders/$orderId': typeof ProductionOrdersOrderIdRoute
  '/production/orders/': typeof ProductionOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/production': typeof ProductionRouteWithChildren
  '/production/cutting-approval': typeof ProductionCuttingApprovalRoute
  '/production/rm-receipt': typeof ProductionRmReceiptRoute
  '/production/rm-request': typeof ProductionRmRequestRoute
  '/production/stage-tracking': typeof ProductionStageTrackingRoute
  '/production/tds-qc': typeof ProductionTdsQcRoute
  '/production/orders/$orderId': typeof ProductionOrdersOrderIdRoute
  '/production/orders': typeof ProductionOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/production': typeof ProductionRouteWithChildren
  '/production/cutting-approval': typeof ProductionCuttingApprovalRoute
  '/production/orders': typeof ProductionOrdersRouteWithChildren
  '/production/rm-receipt': typeof ProductionRmReceiptRoute
  '/production/rm-request': typeof ProductionRmRequestRoute
  '/production/stage-tracking': typeof ProductionStageTrackingRoute
  '/production/tds-qc': typeof ProductionTdsQcRoute
  '/production/orders/$orderId': typeof ProductionOrdersOrderIdRoute
  '/production/orders/': typeof ProductionOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/production'
    | '/production/cutting-approval'
    | '/production/orders'
    | '/production/rm-receipt'
    | '/production/rm-request'
    | '/production/stage-tracking'
    | '/production/tds-qc'
    | '/production/orders/$orderId'
    | '/production/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/production'
    | '/production/cutting-approval'
    | '/production/rm-receipt'
    | '/production/rm-request'
    | '/production/stage-tracking'
    | '/production/tds-qc'
    | '/production/orders/$orderId'
    | '/production/orders'
  id:
    | '__root__'
    | '/'
    | '/production'
    | '/production/cutting-approval'
    | '/production/orders'
    | '/production/rm-receipt'
    | '/production/rm-request'
    | '/production/stage-tracking'
    | '/production/tds-qc'
    | '/production/orders/$orderId'
    | '/production/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductionRoute: typeof ProductionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/tds-qc': {
      id: '/production/tds-qc'
      path: '/tds-qc'
      fullPath: '/production/tds-qc'
      preLoaderRoute: typeof ProductionTdsQcRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/stage-tracking': {
      id: '/production/stage-tracking'
      path: '/stage-tracking'
      fullPath: '/production/stage-tracking'
      preLoaderRoute: typeof ProductionStageTrackingRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/rm-request': {
      id: '/production/rm-request'
      path: '/rm-request'
      fullPath: '/production/rm-request'
      preLoaderRoute: typeof ProductionRmRequestRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/rm-receipt': {
      id: '/production/rm-receipt'
      path: '/rm-receipt'
      fullPath: '/production/rm-receipt'
      preLoaderRoute: typeof ProductionRmReceiptRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/orders': {
      id: '/production/orders'
      path: '/orders'
      fullPath: '/production/orders'
      preLoaderRoute: typeof ProductionOrdersRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/cutting-approval': {
      id: '/production/cutting-approval'
      path: '/cutting-approval'
      fullPath: '/production/cutting-approval'
      preLoaderRoute: typeof ProductionCuttingApprovalRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/orders/': {
      id: '/production/orders/'
      path: '/'
      fullPath: '/production/orders/'
      preLoaderRoute: typeof ProductionOrdersIndexRouteImport
      parentRoute: typeof ProductionOrdersRoute
    }
    '/production/orders/$orderId': {
      id: '/production/orders/$orderId'
      path: '/$orderId'
      fullPath: '/production/orders/$orderId'
      preLoaderRoute: typeof ProductionOrdersOrderIdRouteImport
      parentRoute: typeof ProductionOrdersRoute
    }
  }
}

interface ProductionOrdersRouteChildren {
  ProductionOrdersOrderIdRoute: typeof ProductionOrdersOrderIdRoute
  ProductionOrdersIndexRoute: typeof ProductionOrdersIndexRoute
}

const ProductionOrdersRouteChildren: ProductionOrdersRouteChildren = {
  ProductionOrdersOrderIdRoute: ProductionOrdersOrderIdRoute,
  ProductionOrdersIndexRoute: ProductionOrdersIndexRoute,
}

const ProductionOrdersRouteWithChildren =
  ProductionOrdersRoute._addFileChildren(ProductionOrdersRouteChildren)

interface ProductionRouteChildren {
  ProductionCuttingApprovalRoute: typeof ProductionCuttingApprovalRoute
  ProductionOrdersRoute: typeof ProductionOrdersRouteWithChildren
  ProductionRmReceiptRoute: typeof ProductionRmReceiptRoute
  ProductionRmRequestRoute: typeof ProductionRmRequestRoute
  ProductionStageTrackingRoute: typeof ProductionStageTrackingRoute
  ProductionTdsQcRoute: typeof ProductionTdsQcRoute
}

const ProductionRouteChildren: ProductionRouteChildren = {
  ProductionCuttingApprovalRoute: ProductionCuttingApprovalRoute,
  ProductionOrdersRoute: ProductionOrdersRouteWithChildren,
  ProductionRmReceiptRoute: ProductionRmReceiptRoute,
  ProductionRmRequestRoute: ProductionRmRequestRoute,
  ProductionStageTrackingRoute: ProductionStageTrackingRoute,
  ProductionTdsQcRoute: ProductionTdsQcRoute,
}

const ProductionRouteWithChildren = ProductionRoute._addFileChildren(
  ProductionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductionRoute: ProductionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
